AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VPCId:
    Type: String
    Description: "ID VPC" 

Resources:
  sgelb:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Allow http to client host
      VpcId:
        Ref: VPCId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0

  sgec2:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: SG for instance
      VpcId:
        Ref: VPCId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0

Outputs:
  SecurityGroupElb:
    Description: "ID for Load Balancer SecurityGroup "
    Value: !Ref sgelb

  SecurityGroupEc2:
    Description: "ID for EC2 SecurityGroup "
    Value: !Ref sgec2